### ISSUE TITLE
Add Basic CSS Styling

### ISSUE THREAD

**Issue by kamekaioken** [kheder-codes/dragonball-attack-viewer#21]
Create or use existing CSS files (e.g., `App.css`, or CSS Modules like `AttackItem.module.css`) to add basic styling for layout, readability, and appearance. Style the list items, grid layout, controls area, and detail view for a clean presentation.

**Acceptance Criteria:**
- AC1: CSS rules are applied to components.
- AC2: List items are visually distinct (borders, padding, shadow).
- AC3: Controls area is visually separated.
- AC4: Detail view has basic formatting.
- AC5: Application is generally readable and presentable.

**Comment by kamekaioken** [comment]
# Info: Use General Project Context for LLMs

For various Large Language Models (LLMs) intended to assist with this project, you can use the general project context.

The relevant information can be found in the file:
[General Project Context](https://github.com/kheder-codes/dragonball-attack-viewer/blob/main/prompts/general_context_prompt.md)

Please consider using this context to help improve the accuracy and relevance of LLM responses related to the project.

**Comment by kamekaioken** [comment]
**Technical Guidance for Issue #21: Add Basic CSS Styling**

*This task involves adding CSS rules to make the application visually presentable. Using CSS Modules is recommended for component-scoped styles.*

1.  **Create/Use CSS Module Files:**
    * `src/App.module.css` (or use `src/App.css`)
    * `src/components/AttackList.module.css`
    * `src/components/AttackItem.module.css`
    * `src/components/SearchFilterControls.module.css`
    * `src/components/AttackDetail.module.css`
2.  **Style `App.module.css` (or `App.css`):** Basic page layout, font.
    ```css
    /* src/App.module.css */
    .appContainer {
      font-family: sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 1rem;
    }

    .appContainer h1 {
      text-align: center;
      color: #333;
      margin-bottom: 1.5rem;
    }
    ```
    *Import and use in `App.tsx`:*
    ```typescript
    import styles from './App.module.css';
    // ...
    return <div className={styles.appContainer}>...</div>;
    ```
3.  **Style `SearchFilterControls.module.css`:** Layout for controls.
    ```css
    /* src/components/SearchFilterControls.module.css */
    .controlsArea {
      margin-bottom: 1.5rem;
      padding: 1rem;
      background-color: #f8f9fa;
      border-radius: 8px;
      display: flex;
      gap: 1rem;
      flex-wrap: wrap;
      align-items: center;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }

    .input, .select {
      padding: 0.75rem 1rem;
      font-size: 1rem;
      border: 1px solid #ced4da;
      border-radius: 4px;
    }

    .input {
      min-width: 250px;
      flex-grow: 1; /* Allow input to grow */
    }

    .select {
      min-width: 200px;
      cursor: pointer;
    }
    ```
    *Import and use in `SearchFilterControls.tsx`:*
    ```typescript
    import styles from './SearchFilterControls.module.css';
    // ...
    <div className={styles.controlsArea}>
      <input className={styles.input} ... />
      <select className={styles.select} ... />
    </div>
    ```
4.  **Style `AttackList.module.css`:** Grid layout, 'no results' message.
    ```css
    /* src/components/AttackList.module.css */
    .listContainer {
      /* Styles for the container if needed */
    }

    .list {
      list-style: none;
      padding: 0;
      margin: 1rem 0 0 0; /* Add margin above list */
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      gap: 1.5rem;
    }

    .noResults {
      text-align: center;
      color: #6c757d;
      margin-top: 3rem;
      font-size: 1.1em;
      font-style: italic;
    }
    ```
    *Import and use in `AttackList.tsx`.*
5.  **Style `AttackItem.module.css`:** Card appearance, hover effect, image sizing.
    ```css
    /* src/components/AttackItem.module.css */
    .item {
      border: 1px solid #e9ecef;
      border-radius: 8px;
      padding: 1rem;
      background-color: #fff;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.08);
      transition: transform 0.2s ease, box-shadow 0.2s ease;
      cursor: pointer;
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
    }

    .item:hover {
      transform: translateY(-5px);
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.12);
    }

    .attackName { /* ... as before ... */ }
    .opponentInfo { /* ... as before ... */ }
    .sagaInfo { /* ... as before ... */ }
    .imagesContainer { /* ... as before ... */ }
    .image { /* ... as before ... */ }
    ```
    *Import and use in `AttackItem.tsx`.*
6.  **Style `AttackDetail.module.css`:** Layout for detail view elements.
    ```css
    /* src/components/AttackDetail.module.css */
    .container {
        border: 1px solid #dee2e6;
        padding: 1.5rem 2rem;
        border-radius: 8px;
        background-color: #fff;
        margin-top: 1rem;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    .backButton { /* ... style the button ... */ }
    .attackName { /* ... style the heading ... */ }
    .attackImage { /* ... style the main image ... */ }
    .sagaText { /* ... style saga text ... */ }
    .opponentSection { /* ... style opponent section ... */ }
    .opponentName { /* ... style opponent name ... */ }
    .opponentImage { /* ... style opponent image ... */ }
    ```
    *Import and use in `AttackDetail.tsx`.*
7.  **Check the app:** The application should now have a much cleaner and more organized appearance, with styled controls, cards, and detail view.

**Acceptance Criteria Met If:**
* CSS rules (preferably via Modules) are applied to the main components (`App`, `SearchFilterControls`, `AttackList`, `AttackItem`, `AttackDetail`).
* List items (`AttackItem`) have distinct card styling (borders, padding, background, shadow).
* The `SearchFilterControls` area is visually grouped and styled.
* The `AttackDetail` view has clear formatting for its content.
* The overall application layout and typography are readable and presentable.
