### ISSUE TITLE
feat(bonus): Implement Animated Transitions

### ISSUE THREAD

**Issue by kamekaioken** [kheder-codes/dragonball-attack-viewer#26]
Use CSS transitions or an animation library (like Framer Motion) to add smooth visual transitions when switching between the `AttackList` view and the `AttackDetail` view in `App.tsx`.

**Acceptance Criteria:**
- AC1: View transitions (list to detail, detail to list) are animated smoothly.
- AC2: Animations are brief and non-disruptive.

**Comment by kamekaioken** [comment]
**Technical Guidance for Issue #26: feat(bonus): Implement Animated Transitions**

*Using CSS Transitions (Simpler Approach)*

1.  **Add Animation State in `App.tsx`:** We need state to control the mounting and visibility phases of the detail view for smooth entry and exit.
    ```typescript
    // src/App.tsx
    import React, { useState, useEffect, /*...*/ } from 'react';
    import './App.css'; // Ensure App.css (or a dedicated animation CSS) is imported

    function App() {
        // ... other states ...
        const [selectedAttack, setSelectedAttack] = useState<AttackItemData | null>(null);
        // --- Animation State ---
        const [isDetailMounted, setIsDetailMounted] = useState(false); // Controls if Detail wrapper is in DOM
        const [isDetailVisible, setIsDetailVisible] = useState(false); // Controls opacity/transform class
        const animationDuration = 300; // ms (match CSS transition duration)
        // ...
    }
    ```
2.  **Update Navigation Handlers in `App.tsx`:** Modify `handleAttackSelect` and `handleGoBack` to manage the animation states.
    ```typescript
    // src/App.tsx
    // ... inside App component ...
    const handleAttackSelect = (attack: AttackItemData) => {
        setSelectedAttack(attack);    // Set data
        setIsDetailMounted(true);     // Mount the wrapper
        // Short delay before making visible allows mounting first
        setTimeout(() => setIsDetailVisible(true), 10);
    };

    const handleGoBack = () => {
        setIsDetailVisible(false); // Start fade-out/slide-out
        // Wait for animation to finish before unmounting & clearing data
        setTimeout(() => {
            setIsDetailMounted(false);
            setSelectedAttack(null);
        }, animationDuration);
    };
    ```
3.  **Modify JSX Structure in `App.tsx`:** Wrap the list view and detail view sections in divs and apply conditional classes based on `isDetailVisible` and `isDetailMounted`.
    ```typescript
    // src/App.tsx
    // ... inside App return ...
    return (
        <div className="App" /* style={styles.appContainer} */>
            <h1>Dragon Ball Attack Viewer</h1>
            {/* Container helps manage positioning during transitions */}
            <div className="view-container" style={{ position: 'relative' }}>

                {/* --- List View Wrapper --- */}
                {/* Always mounted, visibility controlled by class */}
                <div
                    className={`list-view-wrapper ${isDetailVisible ? 'view-hidden' : 'view-visible'}`}
                    style={{ width: '100%' }} // Takes space when visible
                >
                    {!selectedAttack && ( // Render controls only if list is logically visible
                        <SearchFilterControls /* ... props ... */ />
                    )}
                    <AttackList
                        attacks={displayedAttacks}
                        onAttackSelect={handleAttackSelect}
                    />
                </div>

                {/* --- Detail View Wrapper --- */}
                {/* Mounted only when an attack is selected and animation hasn't finished exit */}
                {isDetailMounted && selectedAttack && (
                    <div
                        className={`detail-view-wrapper ${isDetailVisible ? 'view-visible' : 'view-hidden'}`}
                        style={{ width: '100%' }} // Takes space when visible
                    >
                        <AttackDetail
                            selectedAttack={selectedAttack}
                            onGoBack={handleGoBack}
                        />
                    </div>
                )}
            </div>
        </div>
    );
    ```
4.  **Add CSS Styles (`src/App.css` or similar):** Define the transitions and visibility states.
    ```css
    /* src/App.css */
    .view-container {
      position: relative;
      overflow-x: hidden; /* Prevent horizontal scrollbars during slide */
      min-height: 50vh; /* Ensure container has height */
    }

    .list-view-wrapper,
    .detail-view-wrapper {
      width: 100%;
      transition: opacity 300ms ease-in-out, transform 300ms ease-in-out;
      /* Position absolute allows overlap during transition */
      position: absolute;
      top: 0;
      left: 0;
    }

    /* State when visible */
    .view-visible {
      opacity: 1;
      transform: translateX(0);
      pointer-events: auto; /* Interactable */
      position: relative; /* Return to normal flow */
    }

    /* State when hidden */
    .view-hidden {
      opacity: 0;
      pointer-events: none; /* Not interactable */
      position: absolute; /* Keep in DOM but out of flow */
    }

    /* Specific transitions */
    .list-view-wrapper.view-hidden {
      transform: translateX(-40px); /* Slide list left */
    }

    .detail-view-wrapper.view-hidden {
      transform: translateX(40px); /* Detail starts/ends right */
    }
    ```
5.  **Check the app:** Clicking an item should smoothly fade/slide out the list and fade/slide in the detail view. Clicking 'Back' should reverse this transition. Ensure content doesn't jump abruptly.

**Acceptance Criteria Met If:**
* Transitions between the list view and detail view are smooth (e.g., fade and/or slide).
* The animations occur in both directions (list -> detail and detail -> list).
* Animations have a reasonable duration (~300ms) and don't feel sluggish or jarring.
